version: '3.4'

services:
  api:
    image: sharepay.api
    build:
      context: .
      dockerfile: SharePay.APIFunctions/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=SharePay;User=sa;Password=Your_password123;

  ui:
    image: sharepay.ui
    build:
      context: .
      dockerfile: SharePay.UI/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=SharePay;User=sa;Password=Password@123;

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"